# Generated by Django 5.0.6 on 2024-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_inspection_inspector_alter_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='passed',
            field=models.BooleanField(null=True),
        ),
    ]
