# Generated by Django 5.0.6 on 2024-06-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_alter_inspection_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='passed',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
