# Generated by Django 5.0.6 on 2024-06-09 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_alter_inspection_passed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Марка производителя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='ВИН-номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Инспектор'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарии инспектора'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='passed',
            field=models.BooleanField(default='False', null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.car', verbose_name='Машина'),
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('request_type', models.CharField(choices=[('register', 'Register'), ('deregister', 'Deregister')], max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
